# model setting
# path to a pre-trained model, if using one
pretrained: ./training/pretrained/efficientnetb4_bupt_balancedface_fr_random_224_bs256_lr00025_m03/backbone_only_compatible.pth   # path to a pre-trained model, if using one
model_name: efficientnetb4   # model name
backbone_name: efficientnetb4  # backbone name

#backbone setting
backbone_config:
  num_classes: 2
  inc: 3
  dropout: false
  mode: Original

# dataset
#all_dataset: [FaceForensics++, FF-F2F, FF-DF, FF-FS, FF-NT, FaceShifter, DeepFakeDetection, Celeb-DF-v1, Celeb-DF-v2, DFDCP, DFDC, DeeperForensics-1.0, UADFV]
#train_dataset: [FF-NT]
#test_dataset: [FaceForensics++, FF-F2F, FF-DF, FF-FS, FF-NT]

compression: c23  # compression-level for videos
train_batchSize: 128
test_batchSize: 128
workers: 8   # number of data loading workers
frame_num: {'train': 1, 'val': 1, 'test': 1}   # number of frames to use per video in training and testing
resolution: 224   # resolution of output image to network
with_mask: false   # whether to include mask information in the input
with_landmark: false   # whether to include facial landmark information in the input
save_ckpt: true   # whether to save checkpoint
save_feat: true   # whether to save features


# data augmentation
use_data_augmentation: true  # Add this flag to enable/disable data augmentation
data_aug:
  flip_prob: 0.5
  rotate_prob: 0.0
  rotate_limit: [-10, 10]
  blur_prob: 0.5
  blur_limit: [3, 7]
  brightness_prob: 0.5
  brightness_limit: [-0.1, 0.1]
  contrast_limit: [-0.1, 0.1]
  quality_lower: 40
  quality_upper: 100


# mean and std for normalization
mean: [0.5, 0.5, 0.5]
std: [0.5, 0.5, 0.5]

# ---------------------------------------
# OPTIMIZER
# ---------------------------------------
optimizer:
  type: adamw
  adamw:
    lr: 0.0001     
    backbone_lr: 0.0001860175405916609
    head_lr: 1.3365592695055747e-05

    beta1: 0.9
    beta2: 0.999
    eps: 0.00000001 
    weight_decay: 0.0008908380251688442
    amsgrad: false

# ---------------------------------------
# LR SCHEDULER
# ---------------------------------------
lr_scheduler: cosine
lr_T_max: 50
lr_eta_min: 0.000001

# ---------------------------------------
# TRAINING
# ---------------------------------------
nEpochs: 50
start_epoch: 0
save_epoch: 1
rec_iter: 100
logdir: ./saved_models_fr_pretrain
manualSeed: 42
save_ckpt: true
save_feat: false

# ---------------------------------------
# LOSS / METRIC
# ---------------------------------------
loss_func: cross_entropy
losstype: null
metric_scoring: auc

# ---------------------------------------
# CUDA
# ---------------------------------------
cuda: true
cudnn: true


