# ---------------------------------------
# LOGGING
# ---------------------------------------
log_dir: ./logs/testing_bench

# ---------------------------------------
# MODEL
# ---------------------------------------
model_name: swin_detector_custom

# backbone
backbone_model: swin_tiny_patch4_window7_224
pretrained: ./training/pretrained/swin_bupt_balancedface_fr_random_224_bs256_adamw_actualLR1e-4_wu3_cosine_wd005_dp01_s32_m03_fp32/backbone_only_compatible.pth   # path to a pre-trained model, if using one
checkpoint_path: ./training/pretrained/swin_bupt_balancedface_fr_random_224_bs256_adamw_actualLR1e-4_wu3_cosine_wd005_dp01_s32_m03_fp32/backbone_only_compatible.pth   # path to a pre-trained model, if using one



img_size: 224
in_chans: 3

drop_rate: 0.03358038513572719
drop_path_rate: 0

# classifier head
classifier_hidden_dim: 256
classifier_dropout: 0.29053543922651504




# ---------------------------------------
# DATASET
# ---------------------------------------
compression: c23
train_batchSize: 64
test_batchSize: 128
workers: 8
frame_num: {'train': 1, 'val': 1, 'test': 1}

resolution: 224

with_mask: false
with_landmark: false

# ---------------------------------------
# DATA AUGMENTATION
# ---------------------------------------
use_data_augmentation: true
data_aug:
  flip_prob: 0.5
  rotate_prob: 0.0
  rotate_limit: [-10, 10]
  blur_prob: 0.5
  blur_limit: [3, 7]
  brightness_prob: 0.5
  brightness_limit: [-0.1, 0.1]
  contrast_limit: [-0.1, 0.1]
  quality_lower: 40
  quality_upper: 100

# ---------------------------------------
# NORMALIZATION
# ---------------------------------------
# mean and std for normalization
mean: [0.5, 0.5, 0.5]
std: [0.5, 0.5, 0.5]

# ---------------------------------------
# OPTIMIZER
# ---------------------------------------


optimizer:
  type: adamw
  

  adamw:
    lr: 0.0001450322602702605

    backbone_lr: 4.495793033729289e-05
    head_lr: 7.816448422699993e-05

    beta1: 0.9
    beta2: 0.999

    eps: 0.00000001
    weight_decay: 0.003968138924977448
# ---------------------------------------

    amsgrad: false

# ---------------------------------------
# LR SCHEDULER
# ---------------------------------------
lr_scheduler: cosine
warmup_epochs: 5
warmup_start_factor: 0.1
lr_T_max: 45
lr_eta_min: 0.000001

# ---------------------------------------
# TRAINING
# ---------------------------------------
nEpochs: 50

start_epoch: 0
save_epoch: 1

rec_iter: 100

logdir: ./saved_models_fr_pretrain

manualSeed: 42

save_ckpt: true
save_feat: false

# ---------------------------------------
# LOSS / METRIC
# ---------------------------------------
loss_func: cross_entropy
metric_scoring: auc

# ---------------------------------------
# CUDA
# ---------------------------------------
cuda: true
cudnn: true